### PR TITLE
Fix some warnings

### PR DESCRIPTION
**Pull request by remilauzier**

### CODE REVIEW

**Comment by Uriopass** [comment]
Did you derive Debug on most structs and Copy on any struct that could be copy ?
I'm not a fan of the approach. 
First, I value compile time and I think debug derived are not free, and I don't see the point of deriving it if it's not used.
Second, I don't like deriving Copy on big structs (like Config) so that I don't accidentally copy them which can be expensive sometimes.
Can you explain your reasoning?

**Comment by remilauzier** [comment]
I can remove them if you prefer. Was just following some lints.

**Comment by Uriopass** [comment]
Not a fan of missing_debug and missing_copy, I wonder what's the reasoning behind it.

**Comment by Uriopass** [comment]
Well, looks like the only lint left that applied is explicit anonymous lifetimes, which I don't necessarily agree with, but if it's the rust 2018 idiom then fine I guess.
Thanks for the PR, glad you're interested in the project !

**Pull request merged**
